version: '2'
services:
  inviter:
    build: ./inviter/.
    container_name: slack-inviter
    ports:
      - "8888:3000"
    restart: always
  bridge:
    build: ./bridge/docker/.
    container_name: slack-bridge
    restart: always
